import { User, Job, Wallet, NotificationItem, ChatMessage, Rating, Offer } from "@/types";

export const initialCurrentUser: User = {
  id: "user-current",
  email: "satria.freelance@wfa-job.id",
  phone: "+6281298765432",
  name: "Satria Dewantara",
  avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
  activeRole: "WORKER",
  isPhoneVerified: true,
  kycStatus: "VERIFIED",
  tier: "SENIOR",
  gmvRealized: 520, // $520 USD (~Rp 8.840.000)
  bio: "Full-stack UI/UX Designer & Frontend Developer dengan spesialisasi Next.js, Figma, dan branding visual modern.",
  skills: ["Figma", "UI/UX", "Next.js", "Tailwind CSS", "Motion Design", "Logo Design"],
  portfolio: [
    {
      id: "port-1",
      title: "Fintech Dashboard Redesign",
      image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=500&auto=format&fit=crop&q=80",
      link: "https://github.com",
    },
    {
      id: "port-2",
      title: "E-Commerce Mobile App",
      image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=500&auto=format&fit=crop&q=80",
      link: "https://dribbble.com",
    },
  ],
  ratingAverage: 4.9,
  completedJobsCount: 14,
  createdAt: "2026-01-10T08:00:00.000Z",
};

export const mockUsers: Record<string, User> = {
  "user-boss-1": {
    id: "user-boss-1",
    email: "budi.santoso@nusantaradigital.co.id",
    phone: "+6281122334455",
    name: "Budi Santoso (PT Nusantara Digital)",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    activeRole: "BOSS",
    isPhoneVerified: true,
    kycStatus: "VERIFIED",
    tier: "EXPERT",
    gmvRealized: 2650, // $2650 USD
    bio: "Product Director di tech startup Jakarta. Sering mencari talent visual design, video editor, dan dev.",
    ratingAverage: 4.95,
    completedJobsCount: 38,
    createdAt: "2025-11-01T08:00:00.000Z",
  },
  "user-boss-2": {
    id: "user-boss-2",
    email: "clara.agency@lumina.id",
    phone: "+6281355443322",
    name: "Clara Wijaya (Lumina Creative)",
    avatarUrl: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    activeRole: "BOSS",
    isPhoneVerified: true,
    kycStatus: "VERIFIED",
    tier: "SENIOR",
    gmvRealized: 1100, // $1100 USD
    bio: "Creative Lead di agency branding Bandung.",
    ratingAverage: 4.85,
    completedJobsCount: 19,
    createdAt: "2025-12-15T08:00:00.000Z",
  },
  "user-worker-2": {
    id: "user-worker-2",
    email: "rendy.editor@gmail.com",
    name: "Rendy Pratama",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    activeRole: "WORKER",
    isPhoneVerified: true,
    kycStatus: "VERIFIED",
    tier: "EXPERT",
    gmvRealized: 1800,
    ratingAverage: 5.0,
    completedJobsCount: 42,
    createdAt: "2025-10-20T08:00:00.000Z",
  },
};

export const initialJobs: Job[] = [
  {
    id: "job-1",
    bossId: "user-boss-1",
    bossName: "Budi Santoso (PT Nusantara Digital)",
    bossAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bossRating: 4.95,
    bossJobsCompleted: 38,
    title: "Redesign UI Mobile Banking App & Design System Figma (5 Screens)",
    description: "Kami membutuhkan UI/UX Designer berpengalaman untuk merombak flow transfer, dashboard, dan riwayat mutasi aplikasi fintech kami. Style minimalis, dark mode/light mode token, auto-layout rapi dengan standard iOS HIG.",
    category: "Design & Creative",
    mode: "OFFER",
    budget: 200, // $200 USD (~Rp 3.400.000)
    deadline: "2026-09-05T23:59:59.000Z",
    status: "OPEN",
    offersCount: 4,
    createdAt: "2026-08-24T10:00:00.000Z",
    digitalContract: {
      contractNumber: "WFA-OFFER-2026-0881",
      scope: "5 High-fidelity screens, Interactive prototype Figma, component token handover.",
      escrowRule: "100% dana terkunci di Escrow saat pemenang dipilih. Rilis bertahap 2 milestone.",
      autoReleaseHours: 72,
      platformFeePercent: 10,
    },
    milestones: [
      { id: "m-1", jobId: "job-1", title: "Milestone 1: Wireframe & Lo-Fi Exploration", amount: 80, status: "PENDING" },
      { id: "m-2", jobId: "job-1", title: "Milestone 2: Final Hi-Fi Figma + Prototype", amount: 120, status: "PENDING" },
    ],
  },
  {
    id: "job-2",
    bossId: "user-boss-2",
    bossName: "Clara Wijaya (Lumina Creative)",
    bossAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    bossRating: 4.85,
    bossJobsCompleted: 19,
    title: "⚡ Spot Mode: Labeling 50 Data Gambar Makanan Lokal untuk AI Training",
    description: "Microtask cepat! Berikan bounding box dan label tag untuk 50 foto kuliner tradisional Indonesia (Rendang, Sate, Gado-gado, dll) di tool annotator berbasis browser. Durasi per worker max 15 menit.",
    category: "Gaming & Microtask",
    mode: "SPOT",
    budget: 5, // $5 USD (~Rp 85.000)
    deadline: "2026-08-26T18:00:00.000Z",
    status: "OPEN",
    spotLimit: 10,
    spotsClaimedCount: 6,
    createdAt: "2026-08-25T08:00:00.000Z",
    digitalContract: {
      contractNumber: "WFA-SPOT-2026-0412",
      scope: "50 Image annotations on browser tool. Validasi otomatis + manual spot check.",
      escrowRule: "Instant auto-escrow. Dana cair langsung begitu submission terverifikasi.",
      autoReleaseHours: 24,
      platformFeePercent: 10,
    },
    spots: [
      {
        id: "spot-1",
        jobId: "job-2",
        workerId: "user-worker-2",
        workerName: "Rendy Pratama",
        claimedAt: "2026-08-25T14:10:00.000Z",
        expiresAt: "2026-08-25T14:25:00.000Z",
        status: "APPROVED",
      },
    ],
  },
  {
    id: "job-3",
    bossId: "user-boss-1",
    bossName: "Budi Santoso (PT Nusantara Digital)",
    bossAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bossRating: 4.95,
    bossJobsCompleted: 38,
    title: "Integrasi API Midtrans Payment & Webhook pada Backend Next.js",
    description: "Membutuhkan backend developer berpengalaman untuk setup endpoint create snap token, handler webhook event settlement/expire/cancel, dan enkripsi payload signature key.",
    category: "Dev & IT",
    mode: "OFFER",
    budget: 160, // $160 USD (~Rp 2.720.000)
    deadline: "2026-08-30T23:59:59.000Z",
    status: "IN_PROGRESS",
    selectedWorkerId: "user-current",
    selectedWorkerName: "Satria Dewantara",
    selectedOfferPrice: 160,
    offersCount: 3,
    createdAt: "2026-08-23T14:00:00.000Z",
    escrow: {
      id: "escrow-3",
      jobId: "job-3",
      amountUSD: 160,
      status: "LOCKED",
      lockedAt: "2026-08-24T09:00:00.000Z",
      autoReleaseAt: "2026-08-28T09:00:00.000Z",
    },
    milestones: [
      { id: "m-31", jobId: "job-3", title: "Setup API Route & Snap Token Generator", amount: 75, status: "APPROVED", deliverable: "GitHub Pull Request #14 & Postman Collection" },
      { id: "m-32", jobId: "job-3", title: "Webhook Verification & Idempotency Storage", amount: 85, status: "SUBMITTED", deliverable: "Webhook listener route with secret validation" },
    ],
    digitalContract: {
      contractNumber: "WFA-OFFER-2026-0779",
      scope: "Next.js API route payment integration with testing suite.",
      escrowRule: "Dana $160 terkunci di rekening bersama Escrow WFA.",
      autoReleaseHours: 72,
      platformFeePercent: 10,
    },
  },
  {
    id: "job-4",
    bossId: "user-boss-2",
    bossName: "Clara Wijaya (Lumina Creative)",
    bossAvatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80",
    bossRating: 4.85,
    bossJobsCompleted: 19,
    title: "Video Editing 3 Reels/TikTok Hook Dinamis + Subtitle Animasi",
    description: "Format 9:16 vertikal, durasi 45-60 detik per video. Footage mentah sudah disediakan, butuh cut tajam, b-roll sound effect, dan teks bergerak ala Alex Hormozi.",
    category: "Video & Animation",
    mode: "OFFER",
    budget: 70, // $70 USD (~Rp 1.190.000)
    deadline: "2026-08-28T18:00:00.000Z",
    status: "OPEN",
    offersCount: 7,
    createdAt: "2026-08-25T07:30:00.000Z",
    digitalContract: {
      contractNumber: "WFA-OFFER-2026-0922",
      scope: "3 Completed MP4 1080x1920 + Project file Premiere/CapCut.",
      escrowRule: "Full Escrow Lock, garansi 2x revisi minor.",
      autoReleaseHours: 48,
      platformFeePercent: 10,
    },
  },
  {
    id: "job-5",
    bossId: "user-boss-1",
    bossName: "Budi Santoso (PT Nusantara Digital)",
    bossAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    bossRating: 4.95,
    bossJobsCompleted: 38,
    title: "⚡ Spot Mode: Proofreading 10 Artikel SEO Edukasi Finansial",
    description: "Cek typo, tanda baca EYD, keterbacaan, dan konsistensi kata kunci pada 10 artikel 800 kata. Hasil review disubmit via form Google Doc.",
    category: "Writing & Copy",
    mode: "SPOT",
    budget: 7, // $7 USD (~Rp 119.000)
    deadline: "2026-08-27T12:00:00.000Z",
    status: "OPEN",
    spotLimit: 5,
    spotsClaimedCount: 2,
    createdAt: "2026-08-25T09:15:00.000Z",
    digitalContract: {
      contractNumber: "WFA-SPOT-2026-0520",
      scope: "Proofread report with suggested edits on Google Docs.",
      escrowRule: "Direct spot release escrow.",
      autoReleaseHours: 24,
      platformFeePercent: 10,
    },
  },
];

export const initialOffers: Offer[] = [
  {
    id: "offer-101",
    jobId: "job-1",
    workerId: "user-current",
    workerName: "Satria Dewantara",
    workerAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    workerTier: "SENIOR",
    workerRating: 4.9,
    message: "Halo Pak Budi! Saya sudah terbiasa merancang UI fintech dengan atomic design token. Portofolio saya terlampir, siap deliver dalam 4 hari dengan 2 milestone terstruktur.",
    price: 195, // $195 USD
    deliveryDays: 4,
    status: "PENDING",
    createdAt: "2026-08-24T11:20:00.000Z",
  },
  {
    id: "offer-102",
    jobId: "job-1",
    workerId: "user-worker-2",
    workerName: "Rendy Pratama",
    workerAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    workerTier: "EXPERT",
    workerRating: 5.0,
    message: "Siap bantu redesign UI Banking dengan Figma variable components. Sudah mengerjakan 5 project app serupa.",
    price: 200, // $200 USD
    deliveryDays: 3,
    status: "PENDING",
    createdAt: "2026-08-24T12:00:00.000Z",
  },
];

export const initialWallet: Wallet = {
  id: "wallet-user-current",
  userId: "user-current",
  balanceUSD: 250, // $250 USD (~Rp 4.250.000)
  lockedInEscrowUSD: 160, // $160 USD (~Rp 2.720.000)
  transactions: [
    {
      id: "tx-1",
      walletId: "wallet-user-current",
      type: "RELEASE",
      amount: 75,
      status: "SUCCESS",
      refId: "job-3",
      title: "Pencairan Milestone 1 Escrow",
      description: "Dana dilepas oleh Boss (PT Nusantara Digital) untuk Milestone API Route ($75)",
      createdAt: "2026-08-24T15:30:00.000Z",
    },
    {
      id: "tx-2",
      walletId: "wallet-user-current",
      type: "FEE",
      amount: -7.5, // 10% Senior Tier
      status: "SUCCESS",
      refId: "job-3",
      title: "Potongan Platform Commission (10% Senior Tier)",
      description: "Tier Senior fee 10% pada job WFA-OFFER-2026-0779",
      createdAt: "2026-08-24T15:30:05.000Z",
    },
    {
      id: "tx-3",
      walletId: "wallet-user-current",
      type: "TOPUP",
      amount: 182.5,
      status: "SUCCESS",
      refId: "qris-pay-9921",
      title: "Top-Up Saldo ($) via QRIS",
      description: "Metode QRIS Instant - Payment Gateway Settlement ($182.5 / Rp 3.102.500)",
      createdAt: "2026-08-20T10:15:00.000Z",
    },
  ],
};

export const initialNotifications: NotificationItem[] = [
  {
    id: "notif-1",
    userId: "user-current",
    title: "Dana Milestone 1 Dilepas 🎉",
    message: "Boss PT Nusantara Digital telah menyetujui Milestone 1 dan $75 (~Rp 1.275.000) telah masuk ke saldo Anda.",
    type: "ESCROW",
    read: false,
    createdAt: "2026-08-24T15:30:00.000Z",
  },
  {
    id: "notif-2",
    userId: "user-current",
    title: "Tawaran Offer Anda Sedang Ditinjau",
    message: "Offer Anda pada 'Redesign UI Mobile Banking App' masuk daftar shortlist Boss.",
    type: "OFFER",
    read: true,
    createdAt: "2026-08-24T12:30:00.000Z",
  },
  {
    id: "notif-3",
    userId: "user-current",
    title: "Spot Baru Tersedia di Sekitar Anda ⚡",
    message: "Job Spot Mode baru 'Labeling 50 Data Gambar Makanan' ($5) tersedia. Klaim sekarang sebelum slot habis!",
    type: "JOB",
    read: true,
    createdAt: "2026-08-25T08:05:00.000Z",
  },
];

export const initialChatMessages: Record<string, ChatMessage[]> = {
  "job-3": [
    {
      id: "msg-1",
      jobId: "job-3",
      senderId: "user-boss-1",
      senderName: "Budi Santoso",
      senderRole: "BOSS",
      text: "Halo Mas Satria, terima kasih sudah menerima project ini. Mohon pastikan signature key Midtrans diverifikasi menggunakan SHA512 ya.",
      createdAt: "2026-08-23T14:15:00.000Z",
    },
    {
      id: "msg-2",
      jobId: "job-3",
      senderId: "user-current",
      senderName: "Satria Dewantara",
      senderRole: "WORKER",
      text: "Siap Pak Budi! Saya sudah implementasikan crypto HMAC SHA512 dan uji coba payload mock sandbox. Milestone 1 sudah saya submit.",
      createdAt: "2026-08-24T14:00:00.000Z",
    },
    {
      id: "msg-3",
      jobId: "job-3",
      senderId: "user-boss-1",
      senderName: "Budi Santoso",
      senderRole: "BOSS",
      text: "Mantap, Milestone 1 sudah saya approve dan dana escrow $75 sudah saya release ke wallet Anda. Lanjutkan milestone ke-2 ya!",
      createdAt: "2026-08-24T15:30:00.000Z",
    },
  ],
};
